### PR TITLE
Search

### PR DESCRIPTION
**Pull request by benjick**
I made a search thingy

### CODE REVIEW

**Comment by benjick** [comment]
[LGTM](http://lgtm.in/i/O5yV8eilq)

**Comment by benjick** [comment]
MORE GIFS

**Comment by esprimo** [comment]
Is it possible to make the search respect which alkoholtyp is selected and just search in that specific category? Also the same but the other way around so that the category respects what's searched for?

**Comment by benjick** [comment]
@esprimo probably, but then we should get away with categories and just make it a two factor search always. I'll look into to it tomorrow. Should be easy enough

Possible route

```js
FlowRouter.route('/:group/:term?', {
    subscriptions: function(params) {
        this.register('group', Meteor.subscribe('search', params.group, params.term));
    },
    action: function(params) {
    	FlowLayout.render('layout', {main: 'main'});
    }
});
```

Possible publication

```js
Meteor.publish('search', function (group, term) {
	return Booze.find({ 
		$or: [ 
			{ name: { $regex : term, $options:"i" } }, 
			{ name2: { $regex : term, $options:"i" } } 
		] ,
		groupSlug: { $regex : group, $options:"i" }
	}, {
		sort: {apk: -1},
		limit: 50,
	});
});
```

**Comment by benjick** [comment]
@esprimo try this and get back to me

**Comment by benjick** [comment]
Two more fixes. No need to review.

[LGTM](http://lgtm.in/i/Y4fJEBocq)

**Pull request merged**
