### PR TITLE
Converted from blaze to react

### PR DESCRIPTION
**Pull request by benjick**
Might want to split into smaller components in the future but this is a good start

### CODE REVIEW

**Comment by benjick** [comment]
For what it's worth this is using the official Meteor package for React. We're still using the same router (flow-router) coupled with react-layout (from kadira, makers of flow-router) instead of their blaze-layout (used to be called flow-layout).

**Comment by benjick** [comment]
ping

**Comment by benjick** [comment]
hej hur går det

**Comment by martineklund** [comment]
LGTM

**Pull request closed without merging**
